spring.application.name=WebDev

spring.datasource.name=webdeveloper
spring.datasource.url= jdbc:postgresql://localhost:5432/DockumentSystem
spring.datasource.username= postgres
spring.datasource.password= postgre

spring.servlet.multipart.enabled=true
# ???????????? ?????? ?????? ????? (????????, 50MB)
spring.servlet.multipart.max-file-size=1000MB

# ???????????? ?????? ????? ??????? (????????, 100MB)
spring.servlet.multipart.max-request-size=10000MB

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database=postgresql
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
