spring.application.name=WebDev

spring.datasource.name=webdeveloper
spring.datasource.url= jdbc:postgresql://localhost:5432/DockumentSystem
spring.datasource.username= postgres
spring.datasource.password= postgre

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=10000MB

logging.level.org.springframework.security=trace


