spring.application.name=WebDev

spring.datasource.name=webdeveloper
spring.datasource.url= jdbc:postgresql://localhost:5432/DockumentSystem
spring.datasource.username= postgres
spring.datasource.password= postgre

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=10000MB

WebDev.jwt-secret=dfkgjbslkedfgblakerbkq3blktqbn3p4tq3-4tq34ptbq3kj4tb134tp2b34tk-klndrg;
WebDev.jwt-expiration-milliseconds=604800000

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database=postgresql
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
